name: Semgrep
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main"]
  schedule:
    - cron: '41 09 * * *' # Sets Semgrep to scan every day at 09:41 UTC.
    # Time chosen randomly.
permissions:
  contents: read
jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep@sha256:3baabc2ec3fc217903ea716aa21b9faec944879012774312807f68b029666285
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false
      - run: |
         semgrep scan \
            --config auto \
            --config p/phpcs-security-audit \
            --config p/security-audit \
            --config p/secure-defaults \
            --config p/owasp-top-ten \
            --config p/cwe-top-25 \
            --config p/trailofbits
